image: docker:latest
services:
  - docker:18.09.6-dind

stages:
  - build
  - package
  - deploy

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: "tcp://localhost:2375"
  REPOSITORY_IMAGE: "${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_PIPELINE_IID}"
  REPOSITORY_IMAGE_DB: "${CI_REGISTRY}/${CI_PROJECT_PATH}:db-${CI_PIPELINE_IID}"
  MONGO_INITDB_ROOT_USERNAME: "$MONGO_USER"
  MONGO_INITDB_ROOT_PASSWORD: "$MONGO_PASS"
  MONGO_INITDB_DATABASE: "$MONGO_DB"

cache:
  paths:
    - node_modules/

project-build:
  tags:
    - kuber
  image: node:12.13-alpine
  stage: build
  only:
    - dev
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

project-node-image-package:
  tags:
    - kuber
  stage: package
  only:
    - dev
  image: docker:18.09.6-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${CI_REGISTRY}
    - docker build -t ${REPOSITORY_IMAGE} .
    - docker push ${REPOSITORY_IMAGE}


project-db-image-package:
  tags:
    - kuber
  stage: package
  only:
    - dev
  image: docker:18.09.6-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${CI_REGISTRY}
    - docker build -f Dockerfile.mongo -t ${REPOSITORY_IMAGE_DB} .
    - docker push ${REPOSITORY_IMAGE_DB}


project-deploy:
  tags:
    - kuber
  stage: deploy
  only:
    - dev
  image: roffe/kubectl:v1.13.2
  when: manual
  script:
    - NAMESPACE_NAME=$(echo -e gitdep-$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME | tr -d _)
    - CI_PROJECT_NAME=$(echo -e $CI_PROJECT_NAME | tr -d _)
    - HOSTNAME=$(echo -e $CI_PROJECT_PATH | tr '/' '-' | tr '_' '-')

    - kubectl config set-cluster test-cluster --server=$(kubectl describe services | grep IP | sed -E 's/IP:[[:space:]]+//' | sed -E 's/Type:[[:space:]]+//' | tr -d ClusterIP)
    - kubectl create secret -n "$NAMESPACE_NAME" docker-registry gitlab-registry --docker-server="$CI_REGISTRY" --docker-username="$REGISTRY_DEPLOY_LOGIN" --docker-password="$REGISTRY_DEPLOY_TOKEN" --docker-email="$GITLAB_USER_EMAIL" -o yaml --dry-run | kubectl replace -n "$NAMESPACE_NAME" --force -f -

    #Node App Deploy
    - sed -i -e "s@__NAMESPACE_NAME__@${NAMESPACE_NAME}@g" dp.yml
    - sed -i -e "s@__CI_PROJECT_NAME__@${CI_PROJECT_NAME}@g" dp.yml
    - sed -i -e "s@__REPOSITORY_IMAGE__@${REPOSITORY_IMAGE}@g" dp.yml
    - sed -i -e "s@__HOSTNAME__@${HOSTNAME}@g" dp.yml
    - kubectl apply -f dp.yml

    #MongoDB Deploy
    - sed -i -e "s@__NAMESPACE_NAME__@${NAMESPACE_NAME}@g" dp-mongo.yml
    - sed -i -e "s@__CI_PROJECT_NAME__@${CI_PROJECT_NAME}@g" dp-mongo.yml
    - sed -i -e "s@__REPOSITORY_IMAGE_DB__@${REPOSITORY_IMAGE_DB}@g" dp-mongo.yml
    - sed -i -e "s@__MONGO_ROOT_USER__@${MONGO_INITDB_ROOT_USERNAME}@g" dp-mongo.yml
    - sed -i -e "s@__MONGO_ROOT_PASS__@${MONGO_INITDB_ROOT_PASSWORD}@g" dp-mongo.yml
    - sed -i -e "s@__MONGO_INITDB__@${MONGO_INITDB_DATABASE}@g" dp-mongo.yml
    - kubectl apply -f dp-mongo.yml